"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BarChart, Bar, CartesianGrid, Cell, Legend, LineChart, Line, PieChart, Pie, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, BarChart3, ChevronDown, CircleGauge, Download, FileSpreadsheet, LayoutDashboard, Menu, MonitorPlay, Search, Sparkles, Trophy, Tv, Upload, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type RawRow = Record<string, unknown>;
type RecordRow = { date:string; program:string; episodeId:string; topic:string; topicType:string; vdoType:string; platform:string; channel:string; contentId:string; url:string; durationMin:number; views:number; likes:number; comments:number; shares:number; engagement:number; engagementRate:number; ratingTotal:number; ratingBkk:number; ratingUrban:number; ratingBkkUrban:number; ratingRural:number; audienceTotal:number; gmmRating:number; gmmAudience:number; bestOfMonth:string; uploadCount:number; revenue:number };
type CompareRow = {date:string;topic:string;program:string;one:number;gmm:number;oneAudience:number;gmmAudience:number;youtube:number;facebook:number;tiktok:number;engagement:number;page:string};
type CompareSortKey = keyof CompareRow;

const PROGRAMS = ["ถกไม่เถียง", "เงินทองของจริง", "Kidsfun", "Hitzradio"];
const PLATFORM_COLORS:Record<string,string>={YouTube:"#ef4444",Facebook:"#2563eb",TikTok:"#111827",Instagram:"#d946ef",TV:"#10b981"};
const TYPE_COLORS:Record<string,string>={"YouTube Live":"#ef4444","TV Episode":"#2563eb","YouTube Highlight":"#0ea5e9","YouTube Shorts":"#7c3aed","Facebook/IG Reels":"#f59e0b",TikTok:"#0f766e",Other:"#94a3b8"};
const TOPIC_COLORS=["#2563eb","#ef4444","#10b981","#7c3aed","#d946ef","#f59e0b","#64748b","#14b8a6","#fb7185","#f97316"];
const n=(v:unknown)=>{if(typeof v==="number")return Number.isFinite(v)?v:0;const text=String(v??"").trim(),isPercent=text.includes("%"),x=Number(text.replaceAll(",","").replace("%",""));return Number.isFinite(x)?(isPercent?x/100:x):0};
const s=(v:unknown)=>String(v??"").trim();
const pick=(r:RawRow,...keys:string[])=>{for(const key of keys)if(r[key]!==undefined&&r[key]!==null&&r[key]!=="")return r[key];return null};
const excelDate=(v:unknown)=>{if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+Math.round(v)*86400000).toISOString().slice(0,10);const t=s(v);if(/^\d{4}-\d{2}-\d{2}/.test(t))return t.slice(0,10);const m=t.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:""};
const normalizeVdoType=(v:string,p:string)=>{const t=v.toLowerCase();if(p==="TV"||t.includes("tv"))return"TV Episode";if(t.includes("live"))return p==="YouTube"?"YouTube Live":`${p} Live`;if(t.includes("short"))return"YouTube Shorts";if(t.includes("highlight"))return"YouTube Highlight";if(t.includes("reel"))return"Facebook/IG Reels";if(p==="TikTok")return"TikTok";if(p==="YouTube"&&(t.includes("episode")||t.includes("video")))return"YouTube Highlight";return v||"Other"};
const normalizeTopic=(v:string)=>{const x=v.toLowerCase();if(!x)return"ไม่ระบุประเภท";if(x.includes("กัมพูชา"))return"ข่าวไทย–กัมพูชา";if(x.includes("อิหร่าน")||x.includes("สหรัฐ")||x.includes("ต่างประเทศ"))return"ข่าวต่างประเทศ / อิหร่าน–สหรัฐ";if(x.includes("ตำรวจ")||x.includes("อาชญากรรม")||x.includes("สแกม"))return"ข่าวตำรวจ / อาชญากรรม / สแกมเมอร์";if(x.includes("กระแส")||x.includes("viral"))return"ข่าวกระแส / Viral";if(x.includes("ชาวบ้าน"))return"ข่าวชาวบ้าน";if(x.includes("ผู้ว่า")||x.includes("บิ๊กโจ๊ก")||x.includes("บุคคล"))return"ข่าวบุคคล / การเมืองท้องถิ่น";if(x.includes("ประวัติศาสตร์"))return"ประวัติศาสตร์";if(x.includes("พระเครื่อง"))return"พระเครื่อง";if(x.includes("ลูกค้า")||x.includes("งานขอ")||x.includes("branded"))return"งานลูกค้า / Branded Content";if(x.includes("การเมือง"))return"ข่าวการเมือง";return v};

function normalize(r:RawRow):RecordRow{const raw=s(pick(r,"Platform","platform"));const channel=s(pick(r,"Channel","channel","Page Name","page-name"));const platform=raw||(channel.toLowerCase().includes("one")||channel.toLowerCase().includes("gmm")?"TV":"Other");const views=n(pick(r,"Views","views","View"));const likes=n(pick(r,"Likes","likes","Like"));const comments=n(pick(r,"Comments","comments"));const shares=n(pick(r,"Shares","shares","Share"));const engagement=n(pick(r,"Engagement","engagement"))||likes+comments+shares;const rate=n(pick(r,"Engagement_Rate","Engagement Rate","engagement_rate"));const notes=s(pick(r,"Notes","notes"));const gmmRating=n(notes.match(/GMM Rating:\s*([\d,.]+)/i)?.[1]);const gmmAudience=n(notes.match(/GMM Audience:\s*([\d,]+)/i)?.[1]);const sourceAudience=n(pick(r,"TV_Audience_Total"));return{date:excelDate(pick(r,"Date","date","Publish Date")),program:s(pick(r,"Program","รายการ","program"))||"ไม่ระบุรายการ",episodeId:s(pick(r,"Episode_ID","Episode ID")),topic:s(pick(r,"Topic","ประเด็น","Video title")),topicType:normalizeTopic(s(pick(r,"Topic_Type","Topic Type","ประเภทเนื้อหา"))),vdoType:normalizeVdoType(s(pick(r,"VDO_Type","VDO Type","video type")),platform),platform,channel,contentId:s(pick(r,"Content_ID","Content","Video ID")),url:s(pick(r,"URL","Url")),durationMin:n(pick(r,"Duration_Min","Duration Min")),views,likes,comments,shares,engagement,engagementRate:rate||(views?engagement/views:0),ratingTotal:n(pick(r,"TV_Rating_Total","Rating Total")),ratingBkk:n(pick(r,"TV_Rating_15+BKK")),ratingUrban:n(pick(r,"TV_Rating_15+URBAN")),ratingBkkUrban:n(pick(r,"TV_Rating_15+BKK&URBAN")),ratingRural:n(pick(r,"TV_Rating_15+RURAL")),audienceTotal:sourceAudience||(platform==="TV"?views:0),gmmRating,gmmAudience,bestOfMonth:s(pick(r,"Best_of_Month","Best of Month")),uploadCount:n(pick(r,"Upload_Count"))||1,revenue:n(pick(r,"Revenue","Estimated revenue (THB)"))}}
const compact=(v:number)=>new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:2}).format(v||0);
const num=(v:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v||0);
const pct=(v:number)=>`${(v*100).toFixed(2)}%`;
const dateLabel=(d:string)=>d?new Date(`${d}T00:00:00`).toLocaleDateString("th-TH",{day:"2-digit",month:"2-digit"}):"-";
const dateTimeLabel=(value:string)=>new Intl.DateTimeFormat("th-TH",{timeZone:"Asia/Bangkok",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(value));
type DatePreset="ALL"|"TODAY"|"LAST_7_DAYS"|"THIS_MONTH"|"LAST_MONTH"|"THIS_YEAR"|"LAST_YEAR"|"QUARTER_1"|"QUARTER_2"|"QUARTER_3"|"QUARTER_4"|"CUSTOM";
const isoDate=(value:Date)=>value.toISOString().slice(0,10);
function getDatePresetRange(preset:DatePreset,referenceYear?:number){const parts=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).filter(x=>x.type!=="literal").map(x=>[x.type,Number(x.value)]));const today=new Date(Date.UTC(parts.year,parts.month-1,parts.day));const year=parts.year,month=parts.month-1;if(preset==="TODAY")return[isoDate(today),isoDate(today)];if(preset==="LAST_7_DAYS"){const start=new Date(today);start.setUTCDate(start.getUTCDate()-6);return[isoDate(start),isoDate(today)]}if(preset==="THIS_MONTH")return[isoDate(new Date(Date.UTC(year,month,1))),isoDate(today)];if(preset==="LAST_MONTH")return[isoDate(new Date(Date.UTC(year,month-1,1))),isoDate(new Date(Date.UTC(year,month,0)))];if(preset==="THIS_YEAR")return[`${year}-01-01`,isoDate(today)];if(preset==="LAST_YEAR")return[`${year-1}-01-01`,`${year-1}-12-31`];const q=preset.match(/^QUARTER_([1-4])$/);if(q){const targetYear=referenceYear||year,startMonth=(Number(q[1])-1)*3+1,endMonth=startMonth+2,lastDay=new Date(Date.UTC(targetYear,endMonth,0)).getUTCDate();return[`${targetYear}-${String(startMonth).padStart(2,"0")}-01`,`${targetYear}-${String(endMonth).padStart(2,"0")}-${String(lastDay).padStart(2,"0")}`]}return["",""]}
function sumBy<T>(rows:T[],key:(r:T)=>string,value:(r:T)=>number){const m=new Map<string,number>();rows.forEach(r=>m.set(key(r),(m.get(key(r))||0)+value(r)));return[...m].map(([name,total])=>({name,total}))}
function presenter(program:string){return program==="ถกไม่เถียง"?"ทิน โชคกมลกิจ":""}
function explicitGuest(topic:string){const match=topic.match(/(?:แขกรับเชิญ|ผู้ร่วมรายการ|สัมภาษณ์|พูดคุยกับ|พบกับ)\s*[:：\-]?\s*([^|#,!?ฯ\n]{2,60})/i);return match?.[1]?.replace(/\s+/g," ").trim()||""}
function bestFormat(rows:RecordRow[]){const grouped=new Map<string,{name:string;views:number;engagement:number;count:number}>();rows.forEach(r=>{const x=grouped.get(r.vdoType)||{name:r.vdoType,views:0,engagement:0,count:0};x.views+=r.views;x.engagement+=r.engagement;x.count++;grouped.set(r.vdoType,x)});return[...grouped.values()].filter(x=>x.count>=3).map(x=>({...x,avgViews:x.views/x.count,rate:x.views?x.engagement/x.views:0})).sort((a,b)=>(b.avgViews*(1+b.rate*5))-(a.avgViews*(1+a.rate*5)))[0]}
function normalizedTopic(value:string){return value.toLowerCase().split("#")[0].replace(/[^a-z0-9ก-๙]+/g," ").replace(/\s+/g," ").trim()}
function topicSimilarity(a:string,b:string){const left=normalizedTopic(a),right=normalizedTopic(b);if(!left||!right)return 0;if(left===right||left.includes(right)||right.includes(left))return 1;const grams=(text:string)=>{const compactText=text.replaceAll(" ","");const set=new Set<string>();for(let i=0;i<compactText.length-2;i++)set.add(compactText.slice(i,i+3));return set},x=grams(left),y=grams(right);if(!x.size||!y.size)return 0;let common=0;x.forEach(g=>{if(y.has(g))common++});return 2*common/(x.size+y.size)}
function SelectBox({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="filter-box"><span>{label}</span><div><select value={value} onChange={e=>onChange(e.target.value)}><option value="ALL">ทั้งหมด</option>{options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown size={15}/></div></label>}
function Kpi({tone,icon,label,value,detail}:{tone:string;icon:React.ReactNode;label:string;value:string;detail:string}){return <article className={`kpi-card ${tone}`}><div className="kpi-icon">{icon}</div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article>}
function Empty({text="ยังไม่มีข้อมูลสำหรับตัวกรองนี้"}:{text?:string}){return <div className="empty-state"><CircleGauge/><span>{text}</span></div>}
function SortHead({label,column,active,direction,onSort}:{label:string;column:CompareSortKey;active:CompareSortKey;direction:"asc"|"desc";onSort:(key:CompareSortKey)=>void}){return <th><button className="sort-head" onClick={()=>onSort(column)}>{label}<span>{active===column?(direction==="asc"?"▲":"▼"):"↕"}</span></button></th>}
function PerformanceTooltip({active,payload,label,tvMode,chartGrain}:{active?:boolean;payload?:Array<{name?:string;value?:number;color?:string;payload?:{topics?:string[]}}>;label?:string;tvMode:boolean;chartGrain:"day"|"month"|"year"}){if(!active||!payload?.length)return null;const topics=payload[0]?.payload?.topics||[];return <div className="performance-tooltip"><strong>{chartGrain==="day"?dateLabel(String(label)):String(label)}</strong>{payload.map((x,i)=><div className="tooltip-value" key={`${x.name}-${i}`}><i style={{background:x.color||"#1261dc"}}/><span>{x.name}</span><b>{num(Number(x.value||0))}</b></div>)}{tvMode&&topics.length>0&&<div className="tooltip-topics"><span>Topic</span><ul>{topics.slice(0,5).map(x=><li key={x}>{x}</li>)}</ul>{topics.length>5&&<small>และอีก {topics.length-5} ประเด็น</small>}</div>}</div>}
function ViewPie({title,subtitle,data}:{title:string;subtitle:string;data:Array<{name:string;total:number}>}){const total=data.reduce((a,x)=>a+x.total,0);return <article className="panel executive-pie"><div className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{data.length?<div className="mini-pie-wrap"><ResponsiveContainer width="52%" height={205}><PieChart><Pie data={data} dataKey="total" nameKey="name" innerRadius={45} outerRadius={76}>{data.map((_,i)=><Cell key={i} fill={TOPIC_COLORS[i%TOPIC_COLORS.length]}/>)}</Pie><Tooltip formatter={v=>num(Number(v))}/></PieChart></ResponsiveContainer><div className="legend-list">{data.map((x,i)=><div key={x.name}><i style={{background:TOPIC_COLORS[i%TOPIC_COLORS.length]}}/><span>{x.name}</span><b>{total?`${(x.total/total*100).toFixed(1)}%`:"0%"}</b></div>)}</div></div>:<Empty/>}</article>}

export default function Dashboard(){
 const[rows,setRows]=useState<RecordRow[]>([]),[loading,setLoading]=useState(true),[menuOpen,setMenuOpen]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[sheetUrl,setSheetUrl]=useState(""),[sourceName,setSourceName]=useState("Master Data 01/01/2026–28/08/2026"),[uploadedAt,setUploadedAt]=useState("2026-09-01T14:15:00+07:00"),[message,setMessage]=useState("");
 const[program,setProgram]=useState("ALL"),[platform,setPlatform]=useState("ALL"),[vdoType,setVdoType]=useState("ALL"),[topicType,setTopicType]=useState("ALL"),[search,setSearch]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[datePreset,setDatePreset]=useState<DatePreset>("ALL");
 const[grain,setGrain]=useState<"day"|"month"|"year">("day");const fileRef=useRef<HTMLInputElement>(null);
 const[executiveChartType,setExecutiveChartType]=useState<"line"|"bar">("line");
 const[comparePage,setComparePage]=useState(1),[comparePageSize,setComparePageSize]=useState(20),[compareSort,setCompareSort]=useState<CompareSortKey>("date"),[compareDirection,setCompareDirection]=useState<"asc"|"desc">("desc");
 useEffect(()=>{fetch("/master-data.json").then(r=>r.json()).then((data:RawRow[])=>{const x=data.map(normalize).filter(r=>r.date);setRows(x);const d=x.map(r=>r.date).sort();setStartDate(d[0]||"");setEndDate(d.at(-1)||"");setLoading(false)}).catch(()=>{setMessage("โหลดข้อมูลเริ่มต้นไม่สำเร็จ");setLoading(false)})},[]);
 const options=useMemo(()=>({programs:[...new Set([...PROGRAMS,...rows.map(r=>r.program)])].filter(Boolean).sort(),platforms:[...new Set(rows.map(r=>r.platform))].filter(Boolean).sort(),vdoTypes:[...new Set(rows.map(r=>r.vdoType))].filter(Boolean).sort(),topicTypes:[...new Set(rows.map(r=>r.topicType))].filter(Boolean).sort()}),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>(program==="ALL"||r.program===program)&&(platform==="ALL"||r.platform===platform)&&(vdoType==="ALL"||r.vdoType===vdoType)&&(topicType==="ALL"||r.topicType===topicType)&&(!startDate||r.date>=startDate)&&(!endDate||r.date<=endDate)&&(!search||`${r.topic} ${r.program} ${r.channel}`.toLowerCase().includes(search.toLowerCase()))),[rows,program,platform,vdoType,topicType,startDate,endDate,search]);
 const executiveRows=useMemo(()=>rows.filter(r=>(program==="ALL"||r.program===program)&&(vdoType==="ALL"||r.vdoType===vdoType)&&(topicType==="ALL"||r.topicType===topicType)&&(!startDate||r.date>=startDate)&&(!endDate||r.date<=endDate)&&(!search||`${r.topic} ${r.program} ${r.channel}`.toLowerCase().includes(search.toLowerCase()))),[rows,program,vdoType,topicType,startDate,endDate,search]);
 const executiveGrain=useMemo<"day"|"month">(()=>startDate&&endDate&&startDate.slice(0,7)===endDate.slice(0,7)?"day":"month",[startDate,endDate]);
 const digitalVsTv=useMemo(()=>{const m=new Map<string,{date:string;"Digital Views":number;"TV Audience":number}>();executiveRows.forEach(r=>{const key=executiveGrain==="day"?r.date:r.date.slice(0,7),x=m.get(key)||{date:key,"Digital Views":0,"TV Audience":0};if(r.platform==="TV")x["TV Audience"]+=r.audienceTotal+r.gmmAudience;else x["Digital Views"]+=r.views;m.set(key,x)});return[...m.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(executiveGrain==="day"?-31:-24)},[executiveRows,executiveGrain]);
 const programPie=useMemo(()=>sumBy(executiveRows,r=>r.program,r=>r.platform==="TV"?r.audienceTotal+r.gmmAudience:r.views).sort((a,b)=>b.total-a.total).slice(0,8),[executiveRows]);
 const platformPie=useMemo(()=>sumBy(executiveRows,r=>r.platform,r=>r.platform==="TV"?r.audienceTotal+r.gmmAudience:r.views).sort((a,b)=>b.total-a.total).slice(0,8),[executiveRows]);
 const vdoTypePie=useMemo(()=>sumBy(executiveRows,r=>r.vdoType,r=>r.platform==="TV"?r.audienceTotal+r.gmmAudience:r.views).sort((a,b)=>b.total-a.total).slice(0,8),[executiveRows]);
 const digitalFiltered=useMemo(()=>filtered.filter(r=>r.platform!=="TV"),[filtered]);
 const tvMode=platform==="TV";
 const performanceFiltered=useMemo(()=>tvMode?filtered.filter(r=>r.platform==="TV"):digitalFiltered,[tvMode,filtered,digitalFiltered]);
 const performanceValue=(r:RecordRow)=>tvMode?r.audienceTotal+r.gmmAudience:r.views;
 const metrics=useMemo(()=>{const views=performanceFiltered.reduce((a,r)=>a+(tvMode?r.audienceTotal+r.gmmAudience:r.views),0),engagement=performanceFiltered.reduce((a,r)=>a+r.engagement,0),uploads=performanceFiltered.reduce((a,r)=>a+r.uploadCount,0),tvRows=filtered.filter(r=>r.platform==="TV"||r.ratingTotal>0),ratingAvg=tvRows.length?tvRows.reduce((a,r)=>a+r.ratingTotal,0)/tvRows.length:0,tvAudience=tvRows.reduce((a,r)=>a+r.audienceTotal+r.gmmAudience,0),tvEpisodes=tvRows.length,days=new Set(performanceFiltered.map(r=>r.date)).size||1;return{views,engagement,uploads,ratingAvg,tvAudience,tvEpisodes,tvAudienceAvg:tvEpisodes?tvAudience/tvEpisodes:0,engagementRate:views?engagement/views:0,avgDaily:views/days}},[performanceFiltered,filtered,tvMode]);
 const chartGrain=useMemo<"day"|"month"|"year">(()=>tvMode?(startDate&&endDate&&startDate.slice(0,7)===endDate.slice(0,7)?"day":"month"):grain,[tvMode,startDate,endDate,grain]);
 const daily=useMemo(()=>{const m=new Map<string,Record<string,number|string|string[]>>();performanceFiltered.forEach(r=>{const key=chartGrain==="year"?r.date.slice(0,4):chartGrain==="month"?r.date.slice(0,7):r.date;const x=m.get(key)||{date:key,topics:[]};const series=tvMode?"TV Audience":r.vdoType;x[series]=n(x[series])+(tvMode?r.audienceTotal+r.gmmAudience:r.views);const topicList=x.topics as string[];if(r.topic&&!topicList.includes(r.topic))topicList.push(r.topic);m.set(key,x)});return[...m.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(chartGrain==="day"?-31:-24)},[performanceFiltered,chartGrain,tvMode]);
 const types=useMemo(()=>sumBy(performanceFiltered,r=>tvMode?"TV Audience":r.vdoType,r=>tvMode?r.audienceTotal+r.gmmAudience:r.views).sort((a,b)=>b.total-a.total).slice(0,7),[performanceFiltered,tvMode]);const topics=useMemo(()=>sumBy(performanceFiltered,r=>r.topicType,r=>tvMode?r.audienceTotal+r.gmmAudience:r.views).sort((a,b)=>b.total-a.total).slice(0,10),[performanceFiltered,tvMode]);const platforms=useMemo(()=>sumBy(performanceFiltered,r=>r.platform,r=>tvMode?r.audienceTotal+r.gmmAudience:r.views).sort((a,b)=>b.total-a.total),[performanceFiltered,tvMode]);const programs=useMemo(()=>sumBy(performanceFiltered,r=>r.program,r=>tvMode?r.audienceTotal+r.gmmAudience:r.views).sort((a,b)=>b.total-a.total),[performanceFiltered,tvMode]);const top=useMemo(()=>[...performanceFiltered].sort((a,b)=>(tvMode?b.audienceTotal+b.gmmAudience:b.views)-(tvMode?a.audienceTotal+a.gmmAudience:a.views)).slice(0,10),[performanceFiltered,tvMode]);const best=useMemo(()=>[...performanceFiltered].filter(r=>(tvMode?r.audienceTotal+r.gmmAudience:r.views)>0).sort((a,b)=>(tvMode?b.audienceTotal+b.gmmAudience:b.views)-(tvMode?a.audienceTotal+a.gmmAudience:a.views)).slice(0,5),[performanceFiltered,tvMode]);
 const rating=useMemo(()=>{const m=new Map<string,{date:string;total:number;bkk:number;urban:number;bu:number;rural:number;count:number}>();filtered.filter(r=>r.platform==="TV"||r.ratingTotal>0).forEach(r=>{const x=m.get(r.date)||{date:r.date,total:0,bkk:0,urban:0,bu:0,rural:0,count:0};x.total+=r.ratingTotal;x.bkk+=r.ratingBkk;x.urban+=r.ratingUrban;x.bu+=r.ratingBkkUrban;x.rural+=r.ratingRural;x.count++;m.set(r.date,x)});return[...m.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-31).map(x=>({date:x.date,Total:x.total/x.count,"15+BKK":x.bkk/x.count,"15+URBAN":x.urban/x.count,"15+BKK&URBAN":x.bu/x.count,"15+RURAL":x.rural/x.count}))},[filtered]);
 const tvAudience=useMemo(()=>filtered.filter(r=>r.platform==="TV"||r.ratingTotal>0).map(r=>({date:r.date,ONE31:r.audienceTotal,GMM25:r.gmmAudience})).sort((a,b)=>a.date.localeCompare(b.date)).slice(-31),[filtered]);
 const compare=useMemo(()=>{type Cluster=CompareRow&{matchTopic:string;hasTv:boolean};const byDate=new Map<string,RecordRow[]>();filtered.forEach(r=>byDate.set(r.date,[...(byDate.get(r.date)||[]),r]));const result:CompareRow[]=[];const addMetrics=(x:Cluster,r:RecordRow)=>{if(r.platform==="TV"){x.one=r.ratingTotal;x.gmm=r.gmmRating;x.oneAudience+=r.audienceTotal;x.gmmAudience+=r.gmmAudience;x.hasTv=true;if(r.topic){x.topic=r.topic;x.matchTopic=r.topic}if(r.channel)x.page=r.channel}else if(r.platform==="YouTube")x.youtube+=r.views;else if(r.platform==="Facebook"||r.platform==="Instagram")x.facebook+=r.views;else if(r.platform==="TikTok")x.tiktok+=r.views;x.engagement+=r.engagement};for(const[date,dateRows]of byDate){const clusters:Cluster[]=[];const ordered=[...dateRows].sort((a,b)=>(a.platform==="TV"?-1:1)-(b.platform==="TV"?-1:1));for(const r of ordered){const meaningfulProgram=r.program&&r.program!=="ไม่ระบุ"&&r.program!=="ไม่ระบุรายการ";let target=meaningfulProgram?clusters.find(x=>x.hasTv&&x.program===r.program):undefined;if(!target){let best:Cluster|undefined,bestScore=0;for(const x of clusters){if(meaningfulProgram&&x.program!==r.program)continue;const score=topicSimilarity(r.topic||r.episodeId,x.matchTopic);if(score>bestScore){best=x;bestScore=score}}if(best&&bestScore>=0.24)target=best}if(!target){target={date,topic:r.topic||r.episodeId,matchTopic:r.topic||r.episodeId,program:r.program,one:0,gmm:0,oneAudience:0,gmmAudience:0,youtube:0,facebook:0,tiktok:0,engagement:0,page:r.channel,hasTv:false};clusters.push(target)}addMetrics(target,r)}result.push(...clusters.map(({matchTopic:_,hasTv:__,...row})=>row))}return result},[filtered]);
 const compareSorted=useMemo(()=>[...compare].sort((a,b)=>{const av=a[compareSort],bv=b[compareSort];const result=typeof av==="number"&&typeof bv==="number"?av-bv:String(av).localeCompare(String(bv),"th");return compareDirection==="asc"?result:-result}),[compare,compareSort,compareDirection]);
 const comparePageCount=Math.max(1,Math.ceil(compareSorted.length/comparePageSize));
 const compareRows=useMemo(()=>compareSorted.slice((comparePage-1)*comparePageSize,comparePage*comparePageSize),[compareSorted,comparePage,comparePageSize]);
 useEffect(()=>setComparePage(1),[program,platform,vdoType,topicType,startDate,endDate,search,comparePageSize]);
 useEffect(()=>{if(comparePage>comparePageCount)setComparePage(comparePageCount)},[comparePage,comparePageCount]);
 function sortCompare(key:CompareSortKey){if(compareSort===key)setCompareDirection(x=>x==="asc"?"desc":"asc");else{setCompareSort(key);setCompareDirection(key==="date"||typeof compare[0]?.[key]==="number"?"desc":"asc")}setComparePage(1)}
 const platformAnalysis=useMemo(()=>[...new Set(digitalFiltered.map(r=>r.platform))].map(name=>{const items=digitalFiltered.filter(r=>r.platform===name&&r.views>0),top=[...items].sort((a,b)=>b.views-a.views)[0],format=bestFormat(items),topic=sumBy(items,r=>r.topicType,r=>r.views).sort((a,b)=>b.total-a.total)[0];return{name,top,format,topic:topic?.name||"ข้อมูลยังไม่พอ"}}).filter(x=>x.top).sort((a,b)=>(b.top?.views||0)-(a.top?.views||0)),[digitalFiltered]);
 const topicTrend=useMemo(()=>{const dates=digitalFiltered.map(r=>r.date).filter(Boolean).sort(),max=dates.at(-1);if(!max)return[];const end=new Date(`${max}T00:00:00Z`),recentStart=new Date(end);recentStart.setUTCDate(recentStart.getUTCDate()-29);const previousStart=new Date(recentStart);previousStart.setUTCDate(previousStart.getUTCDate()-30);const rs=isoDate(recentStart),ps=isoDate(previousStart);const grouped=new Map<string,{name:string,total:number,recent:number,previous:number}>();digitalFiltered.forEach(r=>{const x=grouped.get(r.topicType)||{name:r.topicType,total:0,recent:0,previous:0};x.total+=r.views;if(r.date>=rs)x.recent+=r.views;else if(r.date>=ps)x.previous+=r.views;grouped.set(r.topicType,x)});return[...grouped.values()].map(x=>({...x,growth:x.previous?(x.recent-x.previous)/x.previous:x.recent?1:0})).sort((a,b)=>b.recent-a.recent).slice(0,5)},[digitalFiltered]);
 const q4Plan=useMemo(()=>{const dates=digitalFiltered.map(r=>r.date).filter(Boolean).sort(),max=dates.at(-1);if(!max)return{topics:[],formats:[]};const start=new Date(`${max}T00:00:00Z`);start.setUTCDate(start.getUTCDate()-89);const recent=digitalFiltered.filter(r=>r.date>=isoDate(start));const topics=sumBy(recent,r=>r.topicType,r=>r.views).sort((a,b)=>b.total-a.total).slice(0,3);const formats=[...new Set(recent.map(r=>r.platform))].map(platform=>({platform,format:bestFormat(recent.filter(r=>r.platform===platform))})).filter(x=>x.format).sort((a,b)=>(b.format?.avgViews||0)-(a.format?.avgViews||0)).slice(0,3);return{topics,formats}},[digitalFiltered]);
 const insights=useMemo(()=>{const t=top[0],p=platforms[0],e=tvMode?undefined:[...performanceFiltered].filter(r=>r.views>=1000).sort((a,b)=>b.engagementRate-a.engagementRate)[0];return[t?`${tvMode?"รายการ TV":"คลิป"} ยอดสูงสุด “${t.topic.slice(0,68)}” ทำ ${compact(tvMode?t.audienceTotal+t.gmmAudience:t.views)} ${tvMode?"Audience":"Views"}`:"ยังไม่มี Top Content",p?`${p.name} คิดเป็น ${metrics.views?((p.total/metrics.views)*100).toFixed(1):0}% ของข้อมูลที่เลือก`:"ยังไม่มีข้อมูลแพลตฟอร์ม",e?`Engagement เด่น “${e.topic.slice(0,58)}” ทำ ${pct(e.engagementRate)} — ควรต่อยอดรูปแบบ ${e.vdoType}`:tvMode?"TV Audience แสดงจาก ONE31 + GMM25 โดยไม่คูณ Rating":"ยังไม่มีข้อมูล Engagement เพียงพอ"]},[top,platforms,performanceFiltered,metrics.views,tvMode]);
 function applyRows(raw:RawRow[],name:string){const x=raw.map(normalize).filter(r=>r.date);if(!x.length)throw new Error("ไม่พบข้อมูลที่มีคอลัมน์ Date");const d=x.map(r=>r.date).sort();setRows(x);setStartDate(d[0]);setEndDate(d.at(-1)||d[0]);setSourceName(name);setUploadedAt(new Date().toISOString());setMessage(`นำเข้า ${num(x.length)} แถวเรียบร้อย`);setSourceOpen(false)}
 async function loadSheet(){setLoading(true);setMessage("");try{const id=sheetUrl.match(/\/spreadsheets\/d\/([\w-]+)/)?.[1],gid=sheetUrl.match(/[?&#]gid=(\d+)/)?.[1]||"0";const url=id?`https://docs.google.com/spreadsheets/d/${id}/export?format=csv&gid=${gid}`:sheetUrl;const r=await fetch(url);if(!r.ok)throw new Error("Google Sheet ต้องตั้งค่าให้ผู้มีลิงก์ดูได้");applyRows(parseCsv(await r.text()),"Google Sheets")}catch(e){setMessage(e instanceof Error?e.message:"นำเข้าไม่สำเร็จ")}finally{setLoading(false)}}
 async function onFile(file?:File){if(!file)return;setLoading(true);try{if(file.name.toLowerCase().endsWith(".csv"))applyRows(parseCsv(await file.text()),file.name);else{const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const sh=wb.Sheets[wb.SheetNames.find(x=>x.toLowerCase().includes("master"))||wb.SheetNames[0]];applyRows(XLSX.utils.sheet_to_json(sh,{defval:null}) as RawRow[],file.name)}}catch(e){setMessage(e instanceof Error?e.message:"อ่านไฟล์ไม่สำเร็จ")}finally{setLoading(false)}}
 function applyDatePreset(value:DatePreset){setDatePreset(value);if(value==="CUSTOM")return;if(value==="ALL"){const dates=rows.map(r=>r.date).sort();setStartDate(dates[0]||"");setEndDate(dates.at(-1)||"");return}const latestYear=Number((rows.map(r=>r.date).sort().at(-1)||endDate||String(new Date().getFullYear())).slice(0,4));const[start,end]=getDatePresetRange(value,latestYear);setStartDate(start);setEndDate(end)}
 function download(){const h=["Date","Program","Topic","Topic Type","VDO Type","Platform","Channel","Digital Views","Engagement","Engagement Rate","TV Rating Score"],body=filtered.map(r=>[r.date,r.program,r.topic,r.topicType,r.vdoType,r.platform,r.channel,r.platform==="TV"?0:r.views,r.engagement,r.engagementRate,r.ratingTotal]);const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const blob=new Blob([[h,...body].map(r=>r.map(esc).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`performance-${startDate}-${endDate}.csv`;a.click();URL.revokeObjectURL(a.href)}
 function reset(){setProgram("ALL");setPlatform("ALL");setVdoType("ALL");setTopicType("ALL");setSearch("");setDatePreset("ALL");const d=rows.map(r=>r.date).sort();setStartDate(d[0]||"");setEndDate(d.at(-1)||"")}
 const nav=[["overview","ภาพรวม",<LayoutDashboard key="a"/>],["ai-analysis","AI Executive Analysis",<Sparkles key="ai"/>],["daily","ประสิทธิภาพรายวัน",<Activity key="b"/>],["programs","รายการ",<MonitorPlay key="c"/>],["platforms","แพลตฟอร์ม",<BarChart3 key="d"/>],["topics","ประเภทเนื้อหา",<Sparkles key="e"/>],["rating","TV Rating",<Tv key="f"/>],["best","Best of Month",<Trophy key="g"/>],["compare","Compare Table",<FileSpreadsheet key="h"/>]];
 return <main className="dashboard-shell"><aside className={`sidebar ${menuOpen?"open":""}`}><div className="brand"><div className="live-mark">LIVE</div><p>ข่าว /</p><h1>ENTERTAINMENT<br/>DASHBOARD</h1></div><nav>{nav.map(([id,label,icon])=><a key={String(id)} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{icon}{label}</a>)}</nav><div className="sidebar-note"><Zap/><div><strong>Data status</strong><span>{num(rows.length)} records</span><small>Metricool delay 2–3 วัน</small></div></div><button className="sidebar-import" onClick={()=>{setSourceOpen(true);setMenuOpen(false)}}><Upload/>Import Excel / CSV</button></aside>
 <section className="workspace" id="overview"><header className="mobile-header"><button onClick={()=>setMenuOpen(!menuOpen)}><Menu/></button><strong>Entertainment Dashboard</strong><button onClick={()=>setSourceOpen(true)}><Upload/></button></header>
 <div className="topbar"><SelectBox label="รายการทั้งหมด" value={program} onChange={setProgram} options={options.programs}/><label className="filter-box date-filter"><span>วันเดือนปี</span><div><select className="quick-range" value={datePreset} onChange={e=>applyDatePreset(e.target.value as DatePreset)}><option value="ALL">ทั้งหมด</option><option value="TODAY">วันนี้</option><option value="LAST_7_DAYS">7 วันล่าสุด</option><option value="THIS_MONTH">เดือนนี้</option><option value="LAST_MONTH">เดือนที่แล้ว</option><option value="THIS_YEAR">ปีนี้</option><option value="LAST_YEAR">ปีที่แล้ว</option><option value="QUARTER_1">ไตรมาส 1 (ม.ค.–มี.ค.)</option><option value="QUARTER_2">ไตรมาส 2 (เม.ย.–มิ.ย.)</option><option value="QUARTER_3">ไตรมาส 3 (ก.ค.–ก.ย.)</option><option value="QUARTER_4">ไตรมาส 4 (ต.ค.–ธ.ค.)</option><option value="CUSTOM">กำหนดเอง</option></select><input className="date-input" type="date" value={startDate} onChange={e=>{setStartDate(e.target.value);setDatePreset("CUSTOM")}}/><b>–</b><input className="date-input" type="date" value={endDate} onChange={e=>{setEndDate(e.target.value);setDatePreset("CUSTOM")}}/></div></label><SelectBox label="Cross Platform" value={platform} onChange={setPlatform} options={options.platforms}/><SelectBox label="VDO Type" value={vdoType} onChange={setVdoType} options={options.vdoTypes}/><SelectBox label="Topic Type" value={topicType} onChange={setTopicType} options={options.topicTypes}/><label className="search-box"><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search: ชื่อประเด็น"/></label><Button variant="outline" onClick={()=>setSourceOpen(true)}><Upload/>นำเข้าข้อมูล</Button></div>
 <div className="status-line"><span>แหล่งข้อมูล: <strong>{sourceName}</strong></span><span>{num(filtered.length)} รายการ</span><span>อัปโหลดล่าสุด: <strong>{dateTimeLabel(uploadedAt)} น.</strong></span>{message&&<span className="status-message">{message}</span>}<button onClick={reset}>ล้างตัวกรอง</button></div>
 <section className="kpi-grid"><Kpi tone="blue" icon={<Activity/>} label={tvMode?"TV Audience ตามช่วงเวลา":"ยอดวิวรวม (Digital Only)"} value={compact(metrics.views)} detail={tvMode?`ONE31 + GMM25 · เฉลี่ย ${compact(metrics.avgDaily)} คน/วัน`:`ไม่รวม TV Audience · เฉลี่ย ${compact(metrics.avgDaily)} ต่อวัน`}/><Kpi tone="green" icon={<BarChart3/>} label="Engagement รวม" value={compact(metrics.engagement)} detail={`${pct(metrics.engagementRate)} Engagement Rate`}/><Kpi tone="violet" icon={<Sparkles/>} label="Engagement Rate" value={pct(metrics.engagementRate)} detail={tvMode?"TV ไม่มี Social Engagement":"Likes + Comments + Shares ÷ Digital Views"}/><Kpi tone="orange" icon={<Upload/>} label="Total Upload" value={num(metrics.uploads)} detail={tvMode?`${num(metrics.tvEpisodes)} TV Episodes`:types.slice(0,3).map(x=>`${x.name} ${performanceFiltered.filter(r=>r.vdoType===x.name).length}`).join(" · ")}/><Kpi tone="sky" icon={<Tv/>} label="TV Audience รวม" value={compact(metrics.tvAudience)} detail={`${num(metrics.tvEpisodes)} ตอน · เฉลี่ย ${compact(metrics.tvAudienceAvg)} คน/ตอน`}/><Kpi tone="sky" icon={<Tv/>} label="TV Rating (Average)" value={metrics.ratingAvg.toFixed(3)} detail="คะแนนจริง · ไม่คูณ 700,000"/></section>
 <section className="insight-strip"><div className="insight-title"><Sparkles/><div><strong>Executive Insights</strong><span>เหตุผลที่คอนเทนต์ทำผลงานดี</span></div></div>{insights.map((x,i)=><p key={i}><b>{i+1}</b>{x}</p>)}</section>
 <section className="executive-view-grid"><article className="panel executive-line"><div className="panel-head"><div><h2>Digital Platform Views vs TV Audience</h2><p>เทียบแนวโน้มทุกแพลตฟอร์ม · {executiveGrain==="day"?"รายวัน":"รายเดือน"} · ไม่คูณ TV Rating</p></div><div className="segmented chart-type-toggle"><button className={executiveChartType==="line"?"active":""} onClick={()=>setExecutiveChartType("line")}>กราฟเส้น</button><button className={executiveChartType==="bar"?"active":""} onClick={()=>setExecutiveChartType("bar")}>กราฟแท่ง</button></div></div><div className="chart-lg">{digitalVsTv.length?<ResponsiveContainer>{executiveChartType==="line"?<LineChart data={digitalVsTv}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="date" tickFormatter={v=>executiveGrain==="day"?dateLabel(v):v} tick={{fontSize:11}}/><YAxis tickFormatter={compact} tick={{fontSize:11}}/><Tooltip formatter={v=>num(Number(v))} labelFormatter={v=>executiveGrain==="day"?dateLabel(String(v)):String(v)}/><Legend/><Line type="monotone" dataKey="Digital Views" stroke="#0757e8" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="TV Audience" stroke="#f59e0b" strokeWidth={3} dot={false}/></LineChart>:<BarChart data={digitalVsTv}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="date" tickFormatter={v=>executiveGrain==="day"?dateLabel(v):v} tick={{fontSize:11}}/><YAxis tickFormatter={compact} tick={{fontSize:11}}/><Tooltip formatter={v=>num(Number(v))} labelFormatter={v=>executiveGrain==="day"?dateLabel(String(v)):String(v)}/><Legend/><Bar dataKey="Digital Views" fill="#0757e8" radius={[4,4,0,0]}/><Bar dataKey="TV Audience" fill="#f59e0b" radius={[4,4,0,0]}/></BarChart>}</ResponsiveContainer>:<Empty/>}</div></article><div className="executive-pies"><ViewPie title="รายการทั้งหมด" subtitle="สัดส่วนยอดวิวตาม Program" data={programPie}/><ViewPie title="Cross Platform" subtitle="สัดส่วน Views / TV Audience" data={platformPie}/><ViewPie title="VDO Type" subtitle="สัดส่วนยอดวิวตามรูปแบบวิดีโอ" data={vdoTypePie}/></div></section>
 <section className="panel ai-analysis" id="ai-analysis"><div className="panel-head"><div><h2>✨ AI Executive Analysis</h2><p>วิเคราะห์ใหม่อัตโนมัติจาก Master Data ตามตัวกรองที่เลือก</p></div><span className="ai-badge">DATA-DRIVEN</span></div><div className="ai-summary-grid"><article><span>เนื้อหายอดสูงสุด</span><strong>{top[0]?.topic||"ไม่มีข้อมูล"}</strong>{top[0]&&<><small>{top[0].platform} · {dateLabel(top[0].date)} · {compact(performanceValue(top[0]))} {tvMode?"Audience":"Views"}</small>{presenter(top[0].program)&&<small>พิธีกร: {presenter(top[0].program)}</small>}{explicitGuest(top[0].topic)&&<small>แขกรับเชิญ: {explicitGuest(top[0].topic)}</small>}</>}</article><article><span>ข่าวที่คนสนใจมากที่สุดใน 30 วันล่าสุด</span><strong>{topicTrend[0]?.name||"ข้อมูลยังไม่พอ"}</strong>{topicTrend[0]&&<small>{compact(topicTrend[0].recent)} Views · แนวโน้ม {topicTrend[0].growth>=0?"เพิ่ม":"ลด"} {Math.abs(topicTrend[0].growth*100).toFixed(1)}%</small>}</article><article><span>ข้อเสนอ Highlight ไตรมาส 4</span><strong>{q4Plan.topics.map(x=>x.name).join(" · ")||"ข้อมูลยังไม่พอ"}</strong><small>คัดจาก Topic Type ที่มียอดวิวสูงใน 90 วันล่าสุด</small></article></div><div className="ai-platform-table table-scroll"><table><thead><tr><th>Platform</th><th>Top Content</th><th>วันที่ลง</th><th>พิธีกร</th><th>แขกรับเชิญ</th><th>Views</th><th>Engagement</th><th>ข่าวที่เด่น</th><th>Content/VDO Type ที่ควรทำต่อ</th></tr></thead><tbody>{platformAnalysis.map(x=><tr key={x.name}><td><b>{x.name}</b></td><td><a href={x.top?.url||undefined} target="_blank">{x.top?.topic||"-"}</a></td><td>{x.top?dateLabel(x.top.date):"-"}</td><td>{x.top&&presenter(x.top.program)||"-"}</td><td>{x.top&&explicitGuest(x.top.topic)||"-"}</td><td>{compact(x.top?.views||0)}</td><td>{pct(x.top?.engagementRate||0)}</td><td>{x.topic}</td><td><b>{x.format?.name||"-"}</b>{x.format&&<small>เฉลี่ย {compact(x.format.avgViews)} Views · ER {pct(x.format.rate)}</small>}</td></tr>)}</tbody></table></div><div className="ai-bottom-grid"><article><h3>แนวโน้ม Topic Type</h3>{topicTrend.map((x,i)=><div className="trend-row" key={x.name}><b>{i+1}</b><span>{x.name}</span><strong>{compact(x.recent)}</strong><em className={x.growth>=0?"up":"down"}>{x.growth>=0?"▲":"▼"} {Math.abs(x.growth*100).toFixed(1)}%</em></div>)}</article><article><h3>แผน Highlight ไตรมาส 4</h3><p>ทำชุดสรุปประเด็นจาก <b>{q4Plan.topics.map(x=>x.name).join(", ")||"Topic ที่มีข้อมูลสูงสุด"}</b></p><p>รูปแบบที่ข้อมูลสนับสนุน: {q4Plan.formats.map(x=><span className="tag" key={x.platform}>{x.platform}: {x.format?.name}</span>)}</p><p className="ai-note">หลักเลือก: ยอดวิวเฉลี่ยต่อชิ้น + Engagement Rate ไม่ใช่ดูยอดรวมอย่างเดียว</p></article></div></section>
 <section className="main-grid" id="daily"><article className="panel wide"><div className="panel-head"><div><h2>{tvMode?"TV Audience ตามช่วงเวลา":"ยอดวิวรวมตามช่วงเวลา"}</h2><p>{tvMode?"ONE31 + GMM25 Audience · Hover เพื่อดู Topic":"แยกตาม VDO Type"}</p></div>{tvMode?<span className="auto-grain">อัตโนมัติ: {chartGrain==="day"?"รายวัน":"รายเดือน"}</span>:<div className="segmented">{(["day","month","year"] as const).map(x=><button key={x} className={grain===x?"active":""} onClick={()=>setGrain(x)}>{x==="day"?"รายวัน":x==="month"?"รายเดือน":"รายปี"}</button>)}</div>}</div><div className="chart-lg">{daily.length?<ResponsiveContainer><BarChart data={daily}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="date" tickFormatter={v=>chartGrain==="day"?dateLabel(v):v} tick={{fontSize:11}}/><YAxis tickFormatter={compact} tick={{fontSize:11}}/><Tooltip content={<PerformanceTooltip tvMode={tvMode} chartGrain={chartGrain}/>}/><Legend/>{types.map(x=><Bar key={x.name} dataKey={x.name} stackId="a" fill={TYPE_COLORS[x.name]||"#94a3b8"}/>)}</BarChart></ResponsiveContainer>:<Empty/>}</div></article>
 <article className="panel" id="topics"><div className="panel-head"><div><h2>สัดส่วนยอดวิวตาม Topic Type</h2><p>ช่วงเวลาที่เลือก</p></div></div><div className="donut-wrap">{topics.length?<><ResponsiveContainer width="52%" height={250}><PieChart><Pie data={topics} dataKey="total" nameKey="name" innerRadius={62} outerRadius={94}>{topics.map((_,i)=><Cell key={i} fill={TOPIC_COLORS[i%10]}/>)}</Pie><Tooltip formatter={v=>num(Number(v))}/></PieChart></ResponsiveContainer><div className="legend-list">{topics.map((x,i)=><div key={x.name}><i style={{background:TOPIC_COLORS[i%10]}}/><span>{x.name}</span><b>{metrics.views?((x.total/metrics.views)*100).toFixed(1):0}%</b></div>)}</div></>:<Empty/>}</div></article>
 <article className="panel table-panel" id="best"><div className="panel-head"><div><h2>Top 10 ประเด็น</h2><p>เรียงตาม{tvMode?" TV Audience":"ยอดวิว"}สูงสุด</p></div><button onClick={download}><Download/>ดาวน์โหลด</button></div><div className="table-scroll"><table><thead><tr><th>#</th><th>ประเด็น</th><th>รายการ</th><th>VDO Type</th><th>Topic Type</th><th>{tvMode?"TV Audience":"ยอดวิว"}</th><th>Engagement</th></tr></thead><tbody>{top.map((r,i)=><tr key={`${r.contentId}-${i}`}><td>{i+1}</td><td><a href={r.url||undefined} target="_blank">{r.topic||"ไม่ระบุประเด็น"}</a></td><td>{r.program}</td><td><span className="tag">{r.vdoType}</span></td><td>{r.topicType}</td><td><div className="metric-bar"><i style={{width:`${top[0]&&performanceValue(top[0])?Math.max(5,performanceValue(r)/performanceValue(top[0])*100):0}%`}}/><b>{compact(performanceValue(r))}</b></div></td><td>{tvMode?"-":pct(r.engagementRate)}</td></tr>)}</tbody></table></div></article>
 <article className="panel" id="platforms"><div className="panel-head"><div><h2>ยอดวิวตามแพลตฟอร์ม</h2><p>รวมทุก Content Type</p></div></div><div className="platform-bars">{platforms.map(x=><div key={x.name}><span className="platform-dot" style={{background:PLATFORM_COLORS[x.name]||"#64748b"}}>{x.name[0]}</span><strong>{x.name}</strong><div><i style={{width:`${platforms[0]?.total?x.total/platforms[0].total*100:0}%`,background:PLATFORM_COLORS[x.name]||"#2563eb"}}/></div><b>{compact(x.total)}</b><small>{metrics.views?((x.total/metrics.views)*100).toFixed(1):0}%</small></div>)}{!platforms.length&&<Empty/>}</div></article>
 <article className="panel wide" id="rating"><div className="panel-head"><div><h2>TV Rating Score</h2><p>แสดงคะแนน Rating จริง — ยังไม่แปลง Rating × 700,000 เป็น Views</p></div></div><div className="chart-lg">{rating.length?<ResponsiveContainer><LineChart data={rating}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="date" tickFormatter={dateLabel} tick={{fontSize:11}}/><YAxis tickFormatter={v=>Number(v).toFixed(2)} tick={{fontSize:11}}/><Tooltip formatter={v=>Number(v).toFixed(3)} labelFormatter={dateLabel}/><Legend/><Line type="monotone" dataKey="Total" stroke="#1d4ed8" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="15+BKK" stroke="#16a34a" dot={false}/><Line type="monotone" dataKey="15+URBAN" stroke="#f59e0b" dot={false}/><Line type="monotone" dataKey="15+BKK&URBAN" stroke="#9333ea" dot={false}/><Line type="monotone" dataKey="15+RURAL" stroke="#0891b2" dot={false}/></LineChart></ResponsiveContainer>:<Empty text="ไม่มีข้อมูล TV Rating ในช่วงที่เลือก"/>}</div></article>
 <article className="panel"><div className="panel-head"><div><h2>TV Audience</h2><p>จำนวนผู้ชมจริงจากไฟล์ Master Data</p></div></div><div className="chart-lg">{tvAudience.length?<ResponsiveContainer><LineChart data={tvAudience}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="date" tickFormatter={dateLabel} tick={{fontSize:11}}/><YAxis tickFormatter={compact} tick={{fontSize:11}}/><Tooltip formatter={v=>num(Number(v))} labelFormatter={dateLabel}/><Legend/><Line type="monotone" dataKey="ONE31" stroke="#1261dc" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="GMM25" stroke="#f59e0b" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer>:<Empty text="ไม่มีข้อมูล TV Audience ในช่วงที่เลือก"/>}</div></article>
 <article className="panel"><div className="panel-head"><div><h2>Performance by VDO Type</h2><p>สัดส่วนยอดวิว</p></div></div><div className="donut-wrap small">{types.length?<><ResponsiveContainer width="52%" height={230}><PieChart><Pie data={types} dataKey="total" nameKey="name" innerRadius={55} outerRadius={86}>{types.map((x,i)=><Cell key={i} fill={TYPE_COLORS[x.name]||TOPIC_COLORS[i]}/>)}</Pie><Tooltip formatter={v=>num(Number(v))}/></PieChart></ResponsiveContainer><div className="legend-list">{types.map(x=><div key={x.name}><i style={{background:TYPE_COLORS[x.name]||"#64748b"}}/><span>{x.name}</span><b>{metrics.views?((x.total/metrics.views)*100).toFixed(1):0}%</b></div>)}</div></>:<Empty/>}</div></article>
 <article className="panel"><div className="panel-head"><div><h2>Engagement Rate by Topic Type</h2><p>Top 5 · Digital Only</p></div></div><div className="horizontal-bars">{sumBy(digitalFiltered.filter(r=>r.views>0),r=>r.topicType,r=>r.engagement).map(x=>({...x,views:digitalFiltered.filter(r=>r.topicType===x.name).reduce((a,r)=>a+r.views,0)})).map(x=>({...x,rate:x.views?x.total/x.views:0})).sort((a,b)=>b.rate-a.rate).slice(0,5).map(x=><div key={x.name}><span>{x.name}</span><div><i style={{width:`${Math.min(100,x.rate*500)}%`}}/></div><b>{pct(x.rate)}</b></div>)}</div></article>
 <article className="panel best-panel"><div className="panel-head"><div><h2>🏆 Best of Month</h2><p>Top 5</p></div></div><ol>{best.map((r,i)=><li key={`${r.contentId}-${i}`}><b>{i+1}</b><span>{r.topic}</span><strong>{compact(performanceValue(r))}</strong></li>)}</ol></article>
 <article className="panel" id="programs"><div className="panel-head"><div><h2>รายการ (Program) Performance</h2><p>ยอดวิวรวมช่วงที่เลือก</p></div></div><div className="horizontal-bars programs">{programs.map(x=><div key={x.name}><span>{x.name}</span><div><i style={{width:`${programs[0]?.total?x.total/programs[0].total*100:0}%`}}/></div><b>{compact(x.total)}</b></div>)}</div></article></section>
 <section className="panel compare-panel" id="compare"><div className="panel-head"><div><h2>Compare Table — Live & Episode</h2><p>ข้อมูลทั้งหมด {num(compareSorted.length)} รายการ · กดหัวตารางเพื่อ Sort</p></div><Button variant="outline" onClick={download}><Download/>Export CSV</Button></div><div className="table-scroll"><table><thead><tr><SortHead label="วันที่" column="date" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="ประเด็น" column="topic" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="รายการ" column="program" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="ONE31 Rating" column="one" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="ONE31 Audience" column="oneAudience" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="GMM25 Rating" column="gmm" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="GMM25 Audience" column="gmmAudience" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="YouTube Views" column="youtube" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="Facebook/IG Views" column="facebook" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="TikTok Views" column="tiktok" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="Engagement" column="engagement" active={compareSort} direction={compareDirection} onSort={sortCompare}/><SortHead label="Page Name" column="page" active={compareSort} direction={compareDirection} onSort={sortCompare}/></tr></thead><tbody>{compareRows.map((r,i)=><tr key={`${r.date}-${r.topic}-${i}`}><td>{dateLabel(r.date)}</td><td>{r.topic||"-"}</td><td>{r.program}</td><td>{r.one?r.one.toFixed(3):"-"}</td><td>{r.oneAudience?num(r.oneAudience):"-"}</td><td>{r.gmm?r.gmm.toFixed(3):"-"}</td><td>{r.gmmAudience?num(r.gmmAudience):"-"}</td><td>{compact(r.youtube)}</td><td>{compact(r.facebook)}</td><td>{compact(r.tiktok)}</td><td>{compact(r.engagement)}</td><td>{r.page||"-"}</td></tr>)}</tbody></table></div><div className="pagination"><span>หน้า {comparePage} / {comparePageCount}</span><label>แถวต่อหน้า <select value={comparePageSize} onChange={e=>setComparePageSize(Number(e.target.value))}><option value="20">20</option><option value="50">50</option><option value="100">100</option></select></label><button onClick={()=>setComparePage(1)} disabled={comparePage===1}>«</button><button onClick={()=>setComparePage(p=>Math.max(1,p-1))} disabled={comparePage===1}>ก่อนหน้า</button><button onClick={()=>setComparePage(p=>Math.min(comparePageCount,p+1))} disabled={comparePage===comparePageCount}>ถัดไป</button><button onClick={()=>setComparePage(comparePageCount)} disabled={comparePage===comparePageCount}>»</button></div></section>
 <footer><span>Executive Performance Dashboard</span><span>Digital Views แยกจาก TV Rating · Metricool อาจล่าช้า 2–3 วัน</span></footer></section>
 {sourceOpen&&<div className="modal-backdrop" onMouseDown={()=>setSourceOpen(false)}><section className="source-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSourceOpen(false)}><X/></button><div className="modal-icon"><FileSpreadsheet/></div><h2>เชื่อมต่อข้อมูล Dashboard</h2><p>วาง Google Sheets URL ที่เปิดสิทธิ์ให้ผู้มีลิงก์ดูได้ หรืออัปโหลด Master Data เป็น Excel/CSV</p><label><span>Google Sheets URL</span><Input value={sheetUrl} onChange={e=>setSheetUrl(e.target.value)} placeholder="https://docs.google.com/spreadsheets/d/..."/></label><Button onClick={loadSheet} disabled={!sheetUrl||loading}>{loading?"กำลังโหลด...":"เชื่อมต่อ Google Sheet"}</Button><div className="divider"><span>หรือ</span></div><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>onFile(e.target.files?.[0])}/><Button variant="outline" onClick={()=>fileRef.current?.click()}><Upload/>อัปโหลด Excel / CSV</Button><small>รองรับหัวคอลัมน์ตาม Master Data: Date, Program, Topic, Topic_Type, VDO_Type, Platform, Views, Engagement และ TV Rating</small></section></div>}{loading&&<div className="loading-overlay"><div className="loader"/><span>กำลังประมวลผลข้อมูล...</span></div>}</main>
}

function parseCsv(text:string):RawRow[]{const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const headers=(rows.shift()||[]).map(x=>x.trim());return rows.map(v=>Object.fromEntries(headers.map((h,i)=>[h,v[i]??""])))}
