"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BarChart, Bar, CartesianGrid, Cell, Legend, LineChart, Line, PieChart, Pie, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, BarChart3, CalendarDays, ChevronDown, CircleGauge, Download, FileSpreadsheet, LayoutDashboard, Menu, MonitorPlay, Search, Sparkles, Trophy, Tv, Upload, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type RawRow = Record<string, unknown>;
type RecordRow = { date:string; program:string; episodeId:string; topic:string; topicType:string; vdoType:string; platform:string; channel:string; contentId:string; url:string; durationMin:number; views:number; likes:number; comments:number; shares:number; engagement:number; engagementRate:number; ratingTotal:number; ratingBkk:number; ratingUrban:number; ratingBkkUrban:number; ratingRural:number; audienceTotal:number; bestOfMonth:string; uploadCount:number; revenue:number };

const PROGRAMS = ["ถกไม่เถียง", "เงินทองของจริง", "Kidsfun", "Hitzradio"];
const PLATFORM_COLORS:Record<string,string>={YouTube:"#ef4444",Facebook:"#2563eb",TikTok:"#111827",Instagram:"#d946ef",TV:"#10b981"};
const TYPE_COLORS:Record<string,string>={"YouTube Live":"#ef4444","TV Episode":"#2563eb","YouTube Highlight":"#0ea5e9","YouTube Shorts":"#7c3aed","Facebook/IG Reels":"#f59e0b",TikTok:"#0f766e",Other:"#94a3b8"};
const TOPIC_COLORS=["#2563eb","#ef4444","#10b981","#7c3aed","#d946ef","#f59e0b","#64748b","#14b8a6","#fb7185","#f97316"];
const n=(v:unknown)=>{const x=typeof v==="number"?v:Number(String(v??"").replaceAll(",","").replace("%",""));return Number.isFinite(x)?x:0};
const s=(v:unknown)=>String(v??"").trim();
const pick=(r:RawRow,...keys:string[])=>{for(const key of keys)if(r[key]!==undefined&&r[key]!==null&&r[key]!=="")return r[key];return null};
const excelDate=(v:unknown)=>{if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+Math.round(v)*86400000).toISOString().slice(0,10);const t=s(v);if(/^\d{4}-\d{2}-\d{2}/.test(t))return t.slice(0,10);const m=t.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:""};
const normalizeVdoType=(v:string,p:string)=>{const t=v.toLowerCase();if(p==="TV"||t.includes("tv"))return"TV Episode";if(t.includes("live"))return p==="YouTube"?"YouTube Live":`${p} Live`;if(t.includes("short"))return"YouTube Shorts";if(t.includes("highlight"))return"YouTube Highlight";if(t.includes("reel"))return"Facebook/IG Reels";if(p==="TikTok")return"TikTok";if(p==="YouTube"&&(t.includes("episode")||t.includes("video")))return"YouTube Highlight";return v||"Other"};
const normalizeTopic=(v:string)=>{const x=v.toLowerCase();if(!x)return"ไม่ระบุประเภท";if(x.includes("กัมพูชา"))return"ข่าวไทย–กัมพูชา";if(x.includes("อิหร่าน")||x.includes("สหรัฐ")||x.includes("ต่างประเทศ"))return"ข่าวต่างประเทศ / อิหร่าน–สหรัฐ";if(x.includes("ตำรวจ")||x.includes("อาชญากรรม")||x.includes("สแกม"))return"ข่าวตำรวจ / อาชญากรรม / สแกมเมอร์";if(x.includes("กระแส")||x.includes("viral"))return"ข่าวกระแส / Viral";if(x.includes("ชาวบ้าน"))return"ข่าวชาวบ้าน";if(x.includes("ผู้ว่า")||x.includes("บิ๊กโจ๊ก")||x.includes("บุคคล"))return"ข่าวบุคคล / การเมืองท้องถิ่น";if(x.includes("ประวัติศาสตร์"))return"ประวัติศาสตร์";if(x.includes("พระเครื่อง"))return"พระเครื่อง";if(x.includes("ลูกค้า")||x.includes("งานขอ")||x.includes("branded"))return"งานลูกค้า / Branded Content";if(x.includes("การเมือง"))return"ข่าวการเมือง";return v};

function normalize(r:RawRow):RecordRow{const raw=s(pick(r,"Platform","platform"));const channel=s(pick(r,"Channel","channel","Page Name","page-name"));const platform=raw||(channel.toLowerCase().includes("one")||channel.toLowerCase().includes("gmm")?"TV":"Other");const views=n(pick(r,"Views","views","View"));const likes=n(pick(r,"Likes","likes","Like"));const comments=n(pick(r,"Comments","comments"));const shares=n(pick(r,"Shares","shares","Share"));const engagement=n(pick(r,"Engagement","engagement"))||likes+comments+shares;const rate=n(pick(r,"Engagement_Rate","Engagement Rate","engagement_rate"));return{date:excelDate(pick(r,"Date","date","Publish Date")),program:s(pick(r,"Program","รายการ","program"))||"ไม่ระบุรายการ",episodeId:s(pick(r,"Episode_ID","Episode ID")),topic:s(pick(r,"Topic","ประเด็น","Video title")),topicType:normalizeTopic(s(pick(r,"Topic_Type","Topic Type","ประเภทเนื้อหา"))),vdoType:normalizeVdoType(s(pick(r,"VDO_Type","VDO Type","video type")),platform),platform,channel,contentId:s(pick(r,"Content_ID","Content","Video ID")),url:s(pick(r,"URL","Url")),durationMin:n(pick(r,"Duration_Min","Duration Min")),views,likes,comments,shares,engagement,engagementRate:rate||(views?engagement/views:0),ratingTotal:n(pick(r,"TV_Rating_Total","Rating Total")),ratingBkk:n(pick(r,"TV_Rating_15+BKK")),ratingUrban:n(pick(r,"TV_Rating_15+URBAN")),ratingBkkUrban:n(pick(r,"TV_Rating_15+BKK&URBAN")),ratingRural:n(pick(r,"TV_Rating_15+RURAL")),audienceTotal:n(pick(r,"TV_Audience_Total")),bestOfMonth:s(pick(r,"Best_of_Month","Best of Month")),uploadCount:n(pick(r,"Upload_Count"))||1,revenue:n(pick(r,"Revenue","Estimated revenue (THB)"))}}
const compact=(v:number)=>new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:2}).format(v||0);
const num=(v:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v||0);
const pct=(v:number)=>`${(v*100).toFixed(2)}%`;
const dateLabel=(d:string)=>d?new Date(`${d}T00:00:00`).toLocaleDateString("th-TH",{day:"2-digit",month:"2-digit"}):"-";
function sumBy<T>(rows:T[],key:(r:T)=>string,value:(r:T)=>number){const m=new Map<string,number>();rows.forEach(r=>m.set(key(r),(m.get(key(r))||0)+value(r)));return[...m].map(([name,total])=>({name,total}))}
function SelectBox({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="filter-box"><span>{label}</span><div><select value={value} onChange={e=>onChange(e.target.value)}><option value="ALL">ทั้งหมด</option>{options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown size={15}/></div></label>}
function Kpi({tone,icon,label,value,detail}:{tone:string;icon:React.ReactNode;label:string;value:string;detail:string}){return <article className={`kpi-card ${tone}`}><div className="kpi-icon">{icon}</div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article>}
function Empty({text="ยังไม่มีข้อมูลสำหรับตัวกรองนี้"}:{text?:string}){return <div className="empty-state"><CircleGauge/><span>{text}</span></div>}

export default function Dashboard(){
 const[rows,setRows]=useState<RecordRow[]>([]),[loading,setLoading]=useState(true),[menuOpen,setMenuOpen]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[sheetUrl,setSheetUrl]=useState(""),[sourceName,setSourceName]=useState("Master Data.xlsx"),[message,setMessage]=useState("");
 const[program,setProgram]=useState("ALL"),[platform,setPlatform]=useState("ALL"),[vdoType,setVdoType]=useState("ALL"),[topicType,setTopicType]=useState("ALL"),[search,setSearch]=useState(""),[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState("");
 const[grain,setGrain]=useState<"day"|"month"|"year">("day"),[ratingView,setRatingView]=useState<"score"|"audience">("audience");const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch("/master-data.json").then(r=>r.json()).then((data:RawRow[])=>{const x=data.map(normalize).filter(r=>r.date);setRows(x);const d=x.map(r=>r.date).sort();setStartDate(d[0]||"");setEndDate(d.at(-1)||"");setLoading(false)}).catch(()=>{setMessage("โหลดข้อมูลเริ่มต้นไม่สำเร็จ");setLoading(false)})},[]);
 const options=useMemo(()=>({programs:[...new Set([...PROGRAMS,...rows.map(r=>r.program)])].filter(Boolean).sort(),platforms:[...new Set(rows.map(r=>r.platform))].filter(Boolean).sort(),vdoTypes:[...new Set(rows.map(r=>r.vdoType))].filter(Boolean).sort(),topicTypes:[...new Set(rows.map(r=>r.topicType))].filter(Boolean).sort()}),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>(program==="ALL"||r.program===program)&&(platform==="ALL"||r.platform===platform)&&(vdoType==="ALL"||r.vdoType===vdoType)&&(topicType==="ALL"||r.topicType===topicType)&&(!startDate||r.date>=startDate)&&(!endDate||r.date<=endDate)&&(!search||`${r.topic} ${r.program} ${r.channel}`.toLowerCase().includes(search.toLowerCase()))),[rows,program,platform,vdoType,topicType,startDate,endDate,search]);
 const metrics=useMemo(()=>{const views=filtered.reduce((a,r)=>a+r.views,0),engagement=filtered.reduce((a,r)=>a+r.engagement,0),uploads=filtered.reduce((a,r)=>a+r.uploadCount,0),audience=filtered.reduce((a,r)=>a+(r.audienceTotal||r.ratingTotal*700000),0),days=new Set(filtered.map(r=>r.date)).size||1;return{views,engagement,uploads,audience,engagementRate:views?engagement/views:0,avgDaily:views/days}},[filtered]);
 const daily=useMemo(()=>{const m=new Map<string,Record<string,number|string>>();filtered.forEach(r=>{const key=grain==="year"?r.date.slice(0,4):grain==="month"?r.date.slice(0,7):r.date;const x=m.get(key)||{date:key};x[r.vdoType]=n(x[r.vdoType])+r.views;m.set(key,x)});return[...m.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(grain==="day"?-31:-24)},[filtered,grain]);
 const types=useMemo(()=>sumBy(filtered,r=>r.vdoType,r=>r.views).sort((a,b)=>b.total-a.total).slice(0,7),[filtered]);const topics=useMemo(()=>sumBy(filtered,r=>r.topicType,r=>r.views).sort((a,b)=>b.total-a.total).slice(0,10),[filtered]);const platforms=useMemo(()=>sumBy(filtered,r=>r.platform,r=>r.views).sort((a,b)=>b.total-a.total),[filtered]);const programs=useMemo(()=>sumBy(filtered,r=>r.program,r=>r.views).sort((a,b)=>b.total-a.total),[filtered]);const top=useMemo(()=>[...filtered].sort((a,b)=>b.views-a.views).slice(0,10),[filtered]);const best=useMemo(()=>[...filtered].filter(r=>r.views>0).sort((a,b)=>b.views-a.views).slice(0,5),[filtered]);
 const rating=useMemo(()=>{const m=new Map<string,{date:string;total:number;bkk:number;urban:number;bu:number;rural:number;count:number}>();filtered.filter(r=>r.platform==="TV"||r.ratingTotal>0).forEach(r=>{const x=m.get(r.date)||{date:r.date,total:0,bkk:0,urban:0,bu:0,rural:0,count:0};x.total+=r.ratingTotal;x.bkk+=r.ratingBkk;x.urban+=r.ratingUrban;x.bu+=r.ratingBkkUrban;x.rural+=r.ratingRural;x.count++;m.set(r.date,x)});const f=ratingView==="audience"?700000:1;return[...m.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-31).map(x=>({date:x.date,Total:x.total/x.count*f,"15+BKK":x.bkk/x.count*f,"15+URBAN":x.urban/x.count*f,"15+BKK&URBAN":x.bu/x.count*f,"15+RURAL":x.rural/x.count*f}))},[filtered,ratingView]);
 const compare=useMemo(()=>{const m=new Map<string,{date:string;topic:string;program:string;one:number;gmm:number;youtube:number;facebook:number;tiktok:number;engagement:number;page:string}>();filtered.forEach(r=>{const k=`${r.date}|${r.topic||r.episodeId}`;const x=m.get(k)||{date:r.date,topic:r.topic,program:r.program,one:0,gmm:0,youtube:0,facebook:0,tiktok:0,engagement:0,page:r.channel};const a=r.audienceTotal||r.ratingTotal*700000;if(r.channel.toLowerCase().includes("one"))x.one+=a;if(r.channel.toLowerCase().includes("gmm"))x.gmm+=a;if(r.platform==="YouTube")x.youtube+=r.views;if(r.platform==="Facebook"||r.platform==="Instagram")x.facebook+=r.views;if(r.platform==="TikTok")x.tiktok+=r.views;x.engagement+=r.engagement;m.set(k,x)});return[...m.values()].sort((a,b)=>Math.max(b.one,b.gmm,b.youtube,b.facebook,b.tiktok)-Math.max(a.one,a.gmm,a.youtube,a.facebook,a.tiktok)).slice(0,50)},[filtered]);
 const insights=useMemo(()=>{const t=top[0],p=platforms[0],e=[...filtered].filter(r=>r.views>=1000).sort((a,b)=>b.engagementRate-a.engagementRate)[0];return[t?`คลิปยอดสูงสุด “${t.topic.slice(0,68)}” ทำ ${compact(t.views)} Views บน ${t.platform}`:"ยังไม่มี Top Content",p?`${p.name} เป็นแพลตฟอร์มหลัก ${metrics.views?((p.total/metrics.views)*100).toFixed(1):0}% ของยอดวิวที่เลือก`:"ยังไม่มีข้อมูลแพลตฟอร์ม",e?`Engagement เด่น “${e.topic.slice(0,58)}” ทำ ${pct(e.engagementRate)} — ควรต่อยอดรูปแบบ ${e.vdoType}`:"ยังไม่มีข้อมูล Engagement เพียงพอ"]},[top,platforms,filtered,metrics.views]);
 function applyRows(raw:RawRow[],name:string){const x=raw.map(normalize).filter(r=>r.date);if(!x.length)throw new Error("ไม่พบข้อมูลที่มีคอลัมน์ Date");const d=x.map(r=>r.date).sort();setRows(x);setStartDate(d[0]);setEndDate(d.at(-1)||d[0]);setSourceName(name);setMessage(`นำเข้า ${num(x.length)} แถวเรียบร้อย`);setSourceOpen(false)}
 async function loadSheet(){setLoading(true);setMessage("");try{const id=sheetUrl.match(/\/spreadsheets\/d\/([\w-]+)/)?.[1],gid=sheetUrl.match(/[?&#]gid=(\d+)/)?.[1]||"0";const url=id?`https://docs.google.com/spreadsheets/d/${id}/export?format=csv&gid=${gid}`:sheetUrl;const r=await fetch(url);if(!r.ok)throw new Error("Google Sheet ต้องตั้งค่าให้ผู้มีลิงก์ดูได้");applyRows(parseCsv(await r.text()),"Google Sheets")}catch(e){setMessage(e instanceof Error?e.message:"นำเข้าไม่สำเร็จ")}finally{setLoading(false)}}
 async function onFile(file?:File){if(!file)return;setLoading(true);try{if(file.name.toLowerCase().endsWith(".csv"))applyRows(parseCsv(await file.text()),file.name);else{const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const sh=wb.Sheets[wb.SheetNames.find(x=>x.toLowerCase().includes("master"))||wb.SheetNames[0]];applyRows(XLSX.utils.sheet_to_json(sh,{defval:null}) as RawRow[],file.name)}}catch(e){setMessage(e instanceof Error?e.message:"อ่านไฟล์ไม่สำเร็จ")}finally{setLoading(false)}}
 function download(){const h=["Date","Program","Topic","Topic Type","VDO Type","Platform","Channel","Views","Engagement","Engagement Rate","TV Rating","TV Audience"],body=filtered.map(r=>[r.date,r.program,r.topic,r.topicType,r.vdoType,r.platform,r.channel,r.views,r.engagement,r.engagementRate,r.ratingTotal,r.audienceTotal||r.ratingTotal*700000]);const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const blob=new Blob([[h,...body].map(r=>r.map(esc).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`performance-${startDate}-${endDate}.csv`;a.click();URL.revokeObjectURL(a.href)}
 function reset(){setProgram("ALL");setPlatform("ALL");setVdoType("ALL");setTopicType("ALL");setSearch("");const d=rows.map(r=>r.date).sort();setStartDate(d[0]||"");setEndDate(d.at(-1)||"")}
 const nav=[["overview","ภาพรวม",<LayoutDashboard key="a"/>],["daily","ประสิทธิภาพรายวัน",<Activity key="b"/>],["programs","รายการ",<MonitorPlay key="c"/>],["platforms","แพลตฟอร์ม",<BarChart3 key="d"/>],["topics","ประเภทเนื้อหา",<Sparkles key="e"/>],["rating","TV Rating",<Tv key="f"/>],["best","Best of Month",<Trophy key="g"/>],["compare","Compare Table",<FileSpreadsheet key="h"/>]];
 return <main className="dashboard-shell"><aside className={`sidebar ${menuOpen?"open":""}`}><div className="brand"><div className="live-mark">LIVE</div><p>ข่าว /</p><h1>ENTERTAINMENT<br/>DASHBOARD</h1></div><nav>{nav.map(([id,label,icon])=><a key={String(id)} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{icon}{label}</a>)}</nav><div className="sidebar-note"><Zap/><div><strong>Data status</strong><span>{num(rows.length)} records</span><small>Metricool delay 2–3 วัน</small></div></div></aside>
 <section className="workspace" id="overview"><header className="mobile-header"><button onClick={()=>setMenuOpen(!menuOpen)}><Menu/></button><strong>Entertainment Dashboard</strong><button onClick={()=>setSourceOpen(true)}><Upload/></button></header>
 <div className="topbar"><SelectBox label="รายการทั้งหมด" value={program} onChange={setProgram} options={options.programs}/><label className="filter-box date-filter"><span>วันเดือนปี</span><div><CalendarDays size={15}/><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/><b>–</b><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></div></label><SelectBox label="Cross Platform" value={platform} onChange={setPlatform} options={options.platforms}/><SelectBox label="VDO Type" value={vdoType} onChange={setVdoType} options={options.vdoTypes}/><SelectBox label="Topic Type" value={topicType} onChange={setTopicType} options={options.topicTypes}/><label className="search-box"><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search: ชื่อประเด็น"/></label><Button variant="outline" onClick={()=>setSourceOpen(true)}><Upload/>นำเข้าข้อมูล</Button></div>
 <div className="status-line"><span>แหล่งข้อมูล: <strong>{sourceName}</strong></span><span>{num(filtered.length)} รายการ</span>{message&&<span className="status-message">{message}</span>}<button onClick={reset}>ล้างตัวกรอง</button></div>
 <section className="kpi-grid"><Kpi tone="blue" icon={<Activity/>} label="ยอดวิวรวม" value={compact(metrics.views)} detail={`เฉลี่ย ${compact(metrics.avgDaily)} ต่อวัน`}/><Kpi tone="green" icon={<BarChart3/>} label="Engagement รวม" value={compact(metrics.engagement)} detail={`${pct(metrics.engagementRate)} Engagement Rate`}/><Kpi tone="violet" icon={<Sparkles/>} label="Engagement Rate" value={pct(metrics.engagementRate)} detail="Likes + Comments + Shares ÷ Views"/><Kpi tone="orange" icon={<Upload/>} label="Total Upload" value={num(metrics.uploads)} detail={types.slice(0,3).map(x=>`${x.name} ${filtered.filter(r=>r.vdoType===x.name).length}`).join(" · ")}/><Kpi tone="sky" icon={<Tv/>} label="TV Audience (Total)" value={compact(metrics.audience)} detail="Rating Score × 700,000"/></section>
 <section className="insight-strip"><div className="insight-title"><Sparkles/><div><strong>Executive Insights</strong><span>เหตุผลที่คอนเทนต์ทำผลงานดี</span></div></div>{insights.map((x,i)=><p key={i}><b>{i+1}</b>{x}</p>)}</section>
 <section className="main-grid" id="daily"><article className="panel wide"><div className="panel-head"><div><h2>ยอดวิวรวมตามช่วงเวลา</h2><p>แยกตาม VDO Type</p></div><div className="segmented">{(["day","month","year"] as const).map(x=><button key={x} className={grain===x?"active":""} onClick={()=>setGrain(x)}>{x==="day"?"รายวัน":x==="month"?"รายเดือน":"รายปี"}</button>)}</div></div><div className="chart-lg">{daily.length?<ResponsiveContainer><BarChart data={daily}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="date" tickFormatter={v=>grain==="day"?dateLabel(v):v} tick={{fontSize:11}}/><YAxis tickFormatter={compact} tick={{fontSize:11}}/><Tooltip formatter={v=>num(Number(v))}/><Legend/>{types.map(x=><Bar key={x.name} dataKey={x.name} stackId="a" fill={TYPE_COLORS[x.name]||"#94a3b8"}/>)}</BarChart></ResponsiveContainer>:<Empty/>}</div></article>
 <article className="panel" id="topics"><div className="panel-head"><div><h2>สัดส่วนยอดวิวตาม Topic Type</h2><p>ช่วงเวลาที่เลือก</p></div></div><div className="donut-wrap">{topics.length?<><ResponsiveContainer width="52%" height={250}><PieChart><Pie data={topics} dataKey="total" nameKey="name" innerRadius={62} outerRadius={94}>{topics.map((_,i)=><Cell key={i} fill={TOPIC_COLORS[i%10]}/>)}</Pie><Tooltip formatter={v=>num(Number(v))}/></PieChart></ResponsiveContainer><div className="legend-list">{topics.map((x,i)=><div key={x.name}><i style={{background:TOPIC_COLORS[i%10]}}/><span>{x.name}</span><b>{metrics.views?((x.total/metrics.views)*100).toFixed(1):0}%</b></div>)}</div></>:<Empty/>}</div></article>
 <article className="panel table-panel" id="best"><div className="panel-head"><div><h2>Top 10 ประเด็น</h2><p>เรียงตามยอดวิวสูงสุด</p></div><button onClick={download}><Download/>ดาวน์โหลด</button></div><div className="table-scroll"><table><thead><tr><th>#</th><th>ประเด็น</th><th>รายการ</th><th>VDO Type</th><th>Topic Type</th><th>ยอดวิว</th><th>Engagement</th></tr></thead><tbody>{top.map((r,i)=><tr key={`${r.contentId}-${i}`}><td>{i+1}</td><td><a href={r.url||undefined} target="_blank">{r.topic||"ไม่ระบุประเด็น"}</a></td><td>{r.program}</td><td><span className="tag">{r.vdoType}</span></td><td>{r.topicType}</td><td><div className="metric-bar"><i style={{width:`${top[0]?.views?Math.max(5,r.views/top[0].views*100):0}%`}}/><b>{compact(r.views)}</b></div></td><td>{pct(r.engagementRate)}</td></tr>)}</tbody></table></div></article>
 <article className="panel" id="platforms"><div className="panel-head"><div><h2>ยอดวิวตามแพลตฟอร์ม</h2><p>รวมทุก Content Type</p></div></div><div className="platform-bars">{platforms.map(x=><div key={x.name}><span className="platform-dot" style={{background:PLATFORM_COLORS[x.name]||"#64748b"}}>{x.name[0]}</span><strong>{x.name}</strong><div><i style={{width:`${platforms[0]?.total?x.total/platforms[0].total*100:0}%`,background:PLATFORM_COLORS[x.name]||"#2563eb"}}/></div><b>{compact(x.total)}</b><small>{metrics.views?((x.total/metrics.views)*100).toFixed(1):0}%</small></div>)}{!platforms.length&&<Empty/>}</div></article>
 <article className="panel wide" id="rating"><div className="panel-head"><div><h2>TV Rating</h2><p>{ratingView==="audience"?"จำนวนผู้ชมโดยประมาณ (คะแนน × 700,000)":"คะแนน Rating"} — ONE31 / GMM25</p></div><div className="segmented"><button className={ratingView==="audience"?"active":""} onClick={()=>setRatingView("audience")}>ผู้ชม</button><button className={ratingView==="score"?"active":""} onClick={()=>setRatingView("score")}>คะแนน</button></div></div><div className="chart-lg">{rating.length?<ResponsiveContainer><LineChart data={rating}><CartesianGrid vertical={false} stroke="#e8edf5"/><XAxis dataKey="date" tickFormatter={dateLabel} tick={{fontSize:11}}/><YAxis tickFormatter={compact} tick={{fontSize:11}}/><Tooltip formatter={v=>num(Number(v))} labelFormatter={dateLabel}/><Legend/><Line type="monotone" dataKey="Total" stroke="#1d4ed8" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="15+BKK" stroke="#16a34a" dot={false}/><Line type="monotone" dataKey="15+URBAN" stroke="#f59e0b" dot={false}/><Line type="monotone" dataKey="15+BKK&URBAN" stroke="#9333ea" dot={false}/><Line type="monotone" dataKey="15+RURAL" stroke="#0891b2" dot={false}/></LineChart></ResponsiveContainer>:<Empty text="ไม่มีข้อมูล TV Rating ในช่วงที่เลือก"/>}</div></article>
 <article className="panel"><div className="panel-head"><div><h2>Performance by VDO Type</h2><p>สัดส่วนยอดวิว</p></div></div><div className="donut-wrap small">{types.length?<><ResponsiveContainer width="52%" height={230}><PieChart><Pie data={types} dataKey="total" nameKey="name" innerRadius={55} outerRadius={86}>{types.map((x,i)=><Cell key={i} fill={TYPE_COLORS[x.name]||TOPIC_COLORS[i]}/>)}</Pie><Tooltip formatter={v=>num(Number(v))}/></PieChart></ResponsiveContainer><div className="legend-list">{types.map(x=><div key={x.name}><i style={{background:TYPE_COLORS[x.name]||"#64748b"}}/><span>{x.name}</span><b>{metrics.views?((x.total/metrics.views)*100).toFixed(1):0}%</b></div>)}</div></>:<Empty/>}</div></article>
 <article className="panel"><div className="panel-head"><div><h2>Engagement Rate by Topic Type</h2><p>Top 5</p></div></div><div className="horizontal-bars">{sumBy(filtered.filter(r=>r.views>0),r=>r.topicType,r=>r.engagement).map(x=>({...x,views:filtered.filter(r=>r.topicType===x.name).reduce((a,r)=>a+r.views,0)})).map(x=>({...x,rate:x.views?x.total/x.views:0})).sort((a,b)=>b.rate-a.rate).slice(0,5).map(x=><div key={x.name}><span>{x.name}</span><div><i style={{width:`${Math.min(100,x.rate*500)}%`}}/></div><b>{pct(x.rate)}</b></div>)}</div></article>
 <article className="panel best-panel"><div className="panel-head"><div><h2>🏆 Best of Month</h2><p>Top 5</p></div></div><ol>{best.map((r,i)=><li key={`${r.contentId}-${i}`}><b>{i+1}</b><span>{r.topic}</span><strong>{compact(r.views)}</strong></li>)}</ol></article>
 <article className="panel" id="programs"><div className="panel-head"><div><h2>รายการ (Program) Performance</h2><p>ยอดวิวรวมช่วงที่เลือก</p></div></div><div className="horizontal-bars programs">{programs.map(x=><div key={x.name}><span>{x.name}</span><div><i style={{width:`${programs[0]?.total?x.total/programs[0].total*100:0}%`}}/></div><b>{compact(x.total)}</b></div>)}</div></article></section>
 <section className="panel compare-panel" id="compare"><div className="panel-head"><div><h2>Compare Table — Live & Episode</h2><p>TV ONE31 / GMM25 เทียบ Digital Views และ Engagement</p></div><Button variant="outline" onClick={download}><Download/>Export CSV</Button></div><div className="table-scroll"><table><thead><tr><th>วันที่</th><th>ประเด็น</th><th>รายการ</th><th>TV ONE31</th><th>TV GMM25</th><th>YouTube</th><th>Facebook/IG</th><th>TikTok</th><th>Engagement</th><th>Page Name</th></tr></thead><tbody>{compare.slice(0,20).map((r,i)=><tr key={i}><td>{dateLabel(r.date)}</td><td>{r.topic||"-"}</td><td>{r.program}</td><td>{compact(r.one)}</td><td>{compact(r.gmm)}</td><td>{compact(r.youtube)}</td><td>{compact(r.facebook)}</td><td>{compact(r.tiktok)}</td><td>{compact(r.engagement)}</td><td>{r.page||"-"}</td></tr>)}</tbody></table></div></section>
 <footer><span>Executive Performance Dashboard</span><span>TV audience = Rating × 700,000 · Metricool อาจล่าช้า 2–3 วัน</span></footer></section>
 {sourceOpen&&<div className="modal-backdrop" onMouseDown={()=>setSourceOpen(false)}><section className="source-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSourceOpen(false)}><X/></button><div className="modal-icon"><FileSpreadsheet/></div><h2>เชื่อมต่อข้อมูล Dashboard</h2><p>วาง Google Sheets URL ที่เปิดสิทธิ์ให้ผู้มีลิงก์ดูได้ หรืออัปโหลด Master Data เป็น Excel/CSV</p><label><span>Google Sheets URL</span><Input value={sheetUrl} onChange={e=>setSheetUrl(e.target.value)} placeholder="https://docs.google.com/spreadsheets/d/..."/></label><Button onClick={loadSheet} disabled={!sheetUrl||loading}>{loading?"กำลังโหลด...":"เชื่อมต่อ Google Sheet"}</Button><div className="divider"><span>หรือ</span></div><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>onFile(e.target.files?.[0])}/><Button variant="outline" onClick={()=>fileRef.current?.click()}><Upload/>อัปโหลด Excel / CSV</Button><small>รองรับหัวคอลัมน์ตาม Master Data: Date, Program, Topic, Topic_Type, VDO_Type, Platform, Views, Engagement และ TV Rating</small></section></div>}{loading&&<div className="loading-overlay"><div className="loader"/><span>กำลังประมวลผลข้อมูล...</span></div>}</main>
}

function parseCsv(text:string):RawRow[]{const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const headers=(rows.shift()||[]).map(x=>x.trim());return rows.map(v=>Object.fromEntries(headers.map((h,i)=>[h,v[i]??""])))}
